 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  unav100: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/unav100/train.json
          storage: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/unav100/train.json
        val:
          url: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/unav100/val.json
          storage: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/unav100/val.json
        test:
          url: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/unav100/test.json
          storage: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/unav100/test.json
      videos:
        storage: /home/atuin/g102ea/shared/unav100_dataset/