 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  charades_sta: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /home/atuin/g102ea/shared/charades_sta_annotations/train.json
          storage: /home/atuin/g102ea/shared/charades_sta_annotations/train.json
        val:
          url: /home/atuin/g102ea/shared/charades_sta_annotations/test.json
          storage: /home/atuin/g102ea/shared/charades_sta_annotations/test.json
          # url: Your/path/to/new_val_float.json
          # storage: Your/path/to/new_val_float.json
        test:
          url: /home/atuin/g102ea/shared/charades_sta_annotations/test.json
          storage: /home/atuin/g102ea/shared/charades_sta_annotations/test.json
      videos:
        storage: /home/atuin/g102ea/shared/videos/Charades_v1