 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  charades_sta: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          #url: /home/atuin/g102ea/shared/charades_sta_annotations/train.json
          #storage: /home/atuin/g102ea/shared/charades_sta_annotations/train.json
          #url: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_train.json
          #storage: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_train.json

          url: /home/atuin/g102ea/g102ea13/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_train.json
          storage: /home/atuin/g102ea/g102ea13/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_train.json
        val:
          #url: /home/atuin/g102ea/shared/charades_sta_annotations/test.json
          #storage: /home/atuin/g102ea/shared/charades_sta_annotations/test.json
          #url: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_val.json
          #storage: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_val.json

          url: /home/atuin/g102ea/g102ea13/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_val.json
          storage: /home/atuin/g102ea/g102ea13/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/new_val.json
        test:
          #url: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/test.json
          #storage: /home/atuin/g102ea/g102ea22/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/test.json

          url: /home/atuin/g102ea/g102ea13/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/test.json
          storage: /home/atuin/g102ea/g102ea13/mr-Audio/mr_BLIP_data/Charades_STA_annotations/ablations_split/test.json
      videos:
        storage: /home/atuin/g102ea/shared/videos/Charades_v1
#run:
#  warmup_steps: 0
#  resume_chpt_path: "/home/atuin/g102ea/g102ea13/mr-audio/lavis/result/mr_BLIP/Charades/Charades_mr_audio_attn_fsn_stack_2mha_weighted_sum_changed_prompt-3/checkpoint_best.pth"